name: Performance Testing with k6

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Run Performance Test
        run: k6 run load_test.js
